= Parameters

The parent key for all of the following parameters is `namespaces`.


== `ignoreList`

[horizontal]
type:: array
default:: ['default', 'kube', 'syn']

List of prefixes that are not allowed to be configured.


== `namespaces`

[horizontal]
type:: object
default:: {}

Contains a list of namespaces to create.


== `labelSync`

Configures dynamic Roles and RoleBindings managed by Espejote.

=== `labelSync.ignoredNames`

[horizontal]
type:: list of strings
default:: empty list

A list of namespace names where no labels will be applied.
Entries in the list can be removed by adding the entry prefixed with a `~`.

=== `labelSync.ignoredPrefixes`

[horizontal]
type:: list of strings
default::
+
[source,yaml]
----
labelSync:
  ignoredPrefixes:
    - kube
    - openshift
    - appuio
    - syn
----

A list of namespace name-prefixes where no labels will be applied.
Entries in the list can be removed by adding the entry prefixed with a `~`.

=== `labelSync.applyOnPrefix`

[horizontal]
type:: dict
default:: `{}`
example::
+
[source,yaml]
----
labelSync:
  applyOnPrefix:
    'vshn-postgres': <1>
      'set.rbac.syn.tools/allow-team1': '' <2>
----
<1> Matches all namespaces that start with `vshn-postgres`.
<2> Applies the label `set.rbac.syn.tools/allow-team1=''` to the matching namespace.

Custom set of namespace prefixes, where the listed labels will be applied.

[IMPORTANT]
====
Using this with too broad settings can have unintended sideeffects!
====


== Example

[source,yaml]
----
applications:
  - namespaces as namespaces-team1 <1>

parameters:
  syn:
    teams:
      team1:
        instances:
          - namespaces-team1 <2>

  namespaces_team1:
    namespaces:
      plain-namespace: {}
      with-annotations:
        annotations:
          team: team1
      with-labels:
        labels:
          team: team1
----
<1> Make sure you include the component as an instance.
<2> Make sure you configure ownership of the instance if you are not the cluster owner.
